### ISSUE TITLE
FPS drops to 20. Regardless of the number of render chunks

### ISSUE THREAD

**Issue by MrDenny4** [Parzivail-Modding-Team/LightLevel#10]
Help URGENT! I play on version of minecraft Fabric 1.16.5 (Sodium). When this mod is enabled, the fps is VERY STRONGLY reduced, namely 17-22. I will not install another version, and other "Light Level" mods do not work due to Sodium.

**Comment by parzivail** [comment]
This issue was fixed in more recent versions of the mod, and won't be backported to 1.16. Consider using a different light level mod.

**Comment by MrDenny4** [comment]
Can I ANYWHERE fix this low frame rate bug myself?

**Comment by parzivail** [comment]
Consider using a different light level mod.

**Comment by MrDenny4** [comment]
With Sodium, everything except yours does not work .. Alas. That's why I wanted to ask about fixing the FPS bug

**Comment by MrDenny4** [comment]
Please update to 1.16.5 :(
