### ISSUE TITLE
Is this abandonware?

### ISSUE THREAD

**Issue by BangDroid** [Parzivail-Modding-Team/LightLevel#11]
Is this mod still under development?

I actually really like this implementation of light level overlay, but I am moving to 1.20.4 and struggling to find an equivalent decent light level mod. If anyone has a recommendation I am happy to hear suggestions.

**Comment by parzivail** [comment]
No, I just haven't had time to update it. Thanks for the kind words, I'll see if I can find time this week.

**Comment by BangDroid** [comment]
Oh that sounds great. Yes, I am a big fan of being able to maintain mob protection without having to spam light everywhere, and being able to use low light in moody builds. I don't know how people can do it without quantified data!

**Comment by parzivail** [comment]
Updated to 1.20.4: https://legacy.curseforge.com/minecraft/mc-mods/lightlevel/files/4957866
