### ISSUE TITLE
1.18.1 and new light.

### ISSUE THREAD

**Issue by Mageas** [Parzivail-Modding-Team/LightLevel#6]
Hi, I don't do java (I don't know how to build the project). I wanted to know if it was possible to update the light for the 1.18.x. The mod is already working in 1.18.1.

update:
```java
        if (blockLight < 8) {
            if (skyLight < 8)
                color = 0xFF0000; // Spawn at any time
            else
                color = 0xFFFF00; // Spawn only at night
        }
```

to:
```java
        if (blockLight == 0) {
            if (skyLight == 0)
                color = 0xFF0000; // Spawn at any time
            else
                color = 0xFFFF00; // Spawn only at night
        }
```

**Comment by parzivail** [comment]
Sure, should be an easy fix. I can roll this into #3 and #5 and try to release soon. Been a busy semester and I should have some free time next week to take a look. Thanks for pointing this out!
